CREATE TABLE hits (
  id SERIAL PRIMARY KEY, 
  cell_id INTEGER NOT NULL REFERENCES cells(id),
  note_id INTEGER NOT NULL REFERENCES notes(id),
  charge DECIMAL(9, 9) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE NULL
);