CREATE TABLE notes (
  id SERIAL PRIMARY KEY, 
  source_id INTEGER REFERENCES notes(id),
  target_id INTEGER REFERENCES notes(id),
  list_id INTEGER REFERENCES notes(id),
  token TEXT,
  lat FLOAT,
  lng FLOAT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE NULL
);